AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  postIndexRawDatalambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::324896049972:role/service-role/opensearch_api-role-3t1v0jr8'
      Layers:
        - 'arn:aws:lambda:us-east-1:324896049972:layer:req02:1'
      RuntimePolicy:
        UpdateRuntimeOn: Auto
